-- MySQL Script generated by MySQL Workbench
-- 01/23/19 08:14:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hospital` ;

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8mb4 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`bed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`bed` ;

CREATE TABLE IF NOT EXISTS `hospital`.`bed` (
  `bed_id` INT NOT NULL AUTO_INCREMENT,
  `bed_location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bed_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`tbl_patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`tbl_patient` ;

CREATE TABLE IF NOT EXISTS `hospital`.`tbl_patient` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `bed_id` INT NOT NULL,
  PRIMARY KEY (`patient_id`, `bed_id`),
  INDEX `fk_tbl_patient_bed_idx` (`bed_id` ASC),
  CONSTRAINT `fk_tbl_patient_bed`
    FOREIGN KEY (`bed_id`)
    REFERENCES `hospital`.`bed` (`bed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
